{% set version = "1.3" %}

package:
  name: django-apptemplates
  version: {{ version }}

source:
  fn: django-apptemplates-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/django-apptemplates/django-apptemplates-{{ version }}.tar.gz
  sha256: a3b376181eb6306cfc7532359d4aaf83cf501eff865c8f9bfdf9b5e3930f5986

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - django

test:
  imports:
    - apptemplates
    - apptemplates.test

about:
  home: https://github.com/bittner/django-apptemplates
  license: MIT
  license_file: LICENSE.txt
  summary: 'Django template loader that allows you to load and override a template from a specific Django application.'

extra:
  recipe-maintainers:
    - ocefpaf
