{% set version = "1.4" %}

package:
  name: django-apptemplates
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-apptemplates/django-apptemplates-{{ version }}.tar.gz
  sha256: 9e8b33b156c57ac2a7f6d747faaddfeb27682d7441375e1ee88c220557b36786

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django

test:
  imports:
    - apptemplates
    - apptemplates.test

about:
  home: https://github.com/bittner/django-apptemplates
  license: MIT
  # license_file: LICENSE.txt
  summary: 'Django template loader that allows you to load and override a template from a specific Django application.'

extra:
  recipe-maintainers:
    - ocefpaf
