{% set version = "1.5" %}

package:
  name: django-apptemplates
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-apptemplates/django-apptemplates-{{ version }}.tar.gz
  sha256: c2c46afd3d90827c1d821f137d59e430cb203649aa275b9c2763c871d7545d3f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django

test:
  imports:
    - apptemplates
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bittner/django-apptemplates
  license: MIT
  license_file: LICENSE
  summary: Django template loader that allows you to load and override a template from a specific Django application.

extra:
  recipe-maintainers:
    - ocefpaf
