travis:
  secure:
    BINSTAR_TOKEN: d8rAAAzH+pd8jV1f/cJDpeoBQ5RMMEMpo+1Q0/G9HuLeANWua3tVO4OVNy6VtUoI3j3okuH+Ngyzv2nVueKGLabC2SRzKY8mS4MGhGiSUp/5Kht1HTACEu6O1YBFo0f6/46QqZGhwzhtO5iHN9boYLXaY/q8qmvUsa9qBVnbWJ3A+DGL0xt4k5/9OYNq/+ns0yHqH5lDw3r4ULD7jNZwjJzNDf8iiUp8ACnb6O3V/MEOZRfjCj6h6r7ZR7kdKdaC/3XoeqYsJrLcTuUZOXiu9DKPvns79BVEViR6h2wIsLokORfrF7i3z4IyBr/eTVYIAnBIEHs+1e/wSMre6EHyyykuO28momMeTKcJVwot8wn5dJj4HQhzutRnpRbIe3/hucj+A+omgdz8IpdHq8Wz7HzWRNERAQ2nGfbGYj2c4HWjQvxb3dSRJVCGB9Hn4Ooj11PLIqwqq6yIqtcc2lHzbKxZf1MIarT/TLRO5RDsmDcwrOnCwpigQIGixuxUDd4NImNdoOgixz5dc9yk8e7P2y2TI5BX4ROQnpppCjW+f2IqbfSUVFo5YzsNug8R1zPnceYvLMHXgIcc6DC+W9ZaUHs0+iaVPytjWlTfhw1HQ8eop1KVGYAf2crSD+lfO7kw7poD0MOfF3OYiEy+PM6BhdGuJDQkS1bvBlU4pVGQppA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
