travis:
  secure:
    BINSTAR_TOKEN: 1ccBtjWu6qpoQTZZhQSrSM+My8UuzbbJ8V7XhYx8feJnw2LXVfatVUFnVzX0CtaJ83g0tQlD9f9rjRbD+QyuKbgeR1Zdpv7ErzRjGPrQDDbeDbLY37LHOIAak1dcpjCM/RdJXD6VSdc52zqFZjfTlvgfetQkZsdPHXGtzxg90hP/ipnoAD6jmxFBR+TV/v/UULFUbGuGHtPy8SB4T+sDjRyVPhNfGoKhzOX4sDYcIjZ9SNliCF/G6nQc5sVF+EpR9kAW7Ped4cE7UkGTZZePvAR/IPn5Fwv7NXdo5+uRwlFTwDJ4pKSl5rmJc7+CQNpK5OVO1xUu1dMV781Eys7YxGZbDMk5SZ6yxjsIiyqm9q0rBCMYH0X+2eVQWWCdONahvn//hSIEW8igUWfhHq/0JCzQAUTYOP2g0Im+uXmLTfRsqkNrrnbKioJZNY21dFYo/zYcth55696G06tGGKcKMKBDZUFeJgwZmkcJGLyxJmvtDCJGWT4c0oV7k4aoPs4qPegTB2umflZ0spZyvMaxe0jqATCW+nY8rrgbtxYkVPlWFYAfUaNxUMOGFrrz0XvtMsv2iuLbCoipuNwkR+ZjW+Fw+fg5pc9yZDCt92i88VEWOgQjPP4w2j6UB3G48l+WtbEjsfNnau05+yuv5W7apgJNiMppRjLElk055vXHuuY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
